use_frameworks!

platform :ios, '10.0'

target 'HBCommonModule_Example' do
  pod 'HBCommonModule', :path => '../'
  
  
  pod 'Alamofire'

  target 'HBCommonModule_Tests' do
    inherit! :search_paths

    
  end
end
